### ISSUE TITLE
AttributeError: "EasyDict' object has no attribute'source_subject_no

### ISSUE THREAD

**Issue by morningsunge** [AustinNgs/SFDA#1]
Hello, 
What is the "args.model.source_subject no”?
----------------------------------------------------------------------------
Traceback (most recent call last):
File "main.py",line 75, in <module>totalNet = TotalNet()
File "main.py", line 64, in __init_self__
subjectfusion = AdversarialNetwork(args.model.bottle_neck_dim,args.model.source_subject no)
AttributeError: "EasyDict' object has no attribute'source_subject_no

**Comment by AustinNgs** [comment]
"source_subject_no“ indicates the number of source subject. I fix this issue in pressure-train-config.yaml.
Specifically, if your source domain have 4 sub-datasets (or 4 subjects in our task), the number of source subject is 4.
You can modify the relevant parameters based on your own task in .yaml file.
