### ISSUE TITLE
ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by yuyuyaaa** [AustinNgs/SFDA#2]
Traceback (most recent call last):
  File "main.py", line 219, in <module>
    _,_,domain_prob_discriminator_source = subjectfusion.forward(feature_source)
ValueError: too many values to unpack (expected 3)

**Comment by AustinNgs** [comment]
The error occurs in a simple situation that the output numbers in main.py do no match the setting numbers in net.py
I have modified the output number in main.py
For example: 
_,_,domain_prob_discriminator_source = subjectfusion.forward(feature_source)
should be:
domain_prob_discriminator_source = subjectfusion.forward(feature_source)

You can also check if there are any other errors about this issue. Thanks!

**Comment by yuyuyaaa** [comment]
Thanks for the answer, but this issue has come up again after the revision

Traceback (most recent call last):
  File "main.py", line 241, in <module>
    loss.backward()
  File "/home/hsj/.conda/envs/CUDA11.0/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hsj/.conda/envs/CUDA11.0/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
<traceback object at 0x7496cb456960>
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [2,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [3,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [4,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [7,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [9,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [11,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.

**Comment by AustinNgs** [comment]
This error usually occurs when the output of model didn't match the number of class.
For example, the output of final fc layer should be two when you are doing 2-class training and should be 1 when you are doing adversairal training. Please kindly have a check if you set the suitable value.

**Comment by yuyuyaaa** [comment]
Hello, I changed the num_class:2 in the pressure-train-config.yaml file to train the dataset you provided, and check the labels, etc., but I still get an error and want to know exactly where I should change

Output dimension of classifier: 2
Label source contents: tensor([1, 1, 1, 0, 1], device='cuda:0')
Label source shape: torch.Size([5])
Number of unique classes in label source: 2
Output min: 0.0003814928641077131
Output max: 0.09319763630628586
Output min: 2.882271473936271e-05
Output max: 0.07789629697799683
label_source min: 0 max: 1
predict_prob_source min: 0.49401190876960754 max: 0.5059880614280701
<traceback object at 0x75e543f59910>
Traceback (most recent call last):
  File "main.py", line 263, in <module>
    loss.backward()
  File "/home/hsj/.conda/envs/CUDA11.0/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hsj/.conda/envs/CUDA11.0/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [1,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [2,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [3,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [4,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.

**Comment by AustinNgs** [comment]
Please make sure that the num_class in classifier and DAdiscriminator is different. I suppose that you can check again in the updated .yaml file.
self.classifier = CLS(self.feature_extractor.output_num(), args.train.num_class, bottle_neck_dim=args.model.bottle_neck_dim)
self.DAdiscriminator = AdversarialNetwork(args.model.bottle_neck_dim,args.model.num_class)

**Comment by yuyuyaaa** [comment]
Hello, I modified this sentence do = nn. CrossEntropyLoss(reduction='none')(domain_prob_discriminator_source, label_source), change the original idx_source to label_source and you will be able to run successfully

**Comment by AustinNgs** [comment]
I suppose that this is not the case. "do" loss indicates the subject fusion training where the lable space should be matched to the number of sub-datasets in your source domain, so it is not suitable to map all source subjects into [0,1].

In pressure-train-config.yaml, model.num_class should be set as 1, whereas train.num_class should be set as 2.

And btw, do you split the datasets correctly? There might be some errors in idx labelling.

**Comment by yuyuyaaa** [comment]
I have no problem modifying the pressure-train-config.yaml file, checking the tags gets:
Output dimension of classifier: 2
Label source contents1: tensor([1, 1, 1, 0], device='cuda:0')
Label source shape: torch.Size([4])
Number of unique classes in label source: 2
idx source contents: tensor([11, 34, 27, 23], device='cuda:0')
idx source data type: torch.int64
Unique classes in idx source: tensor([11, 23, 27, 34], device='cuda:0')
idx source min: 11 max: 34
As for dividing the data set, I didn't make any changes to this part of the code

**Comment by yuyuyaaa** [comment]
I've set the model.num_class and train.num_class in pressure-train-config.yaml, and the num_class in the classifier and DA discriminator have been changed as you updated, but I'm still getting errors

Traceback (most recent call last):
  File "main.py", line 281, in <module>
    loss.backward()
  File "/home/hsj/.conda/envs/CUDA11.0/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/hsj/.conda/envs/CUDA11.0/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [1,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [2,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:59: ClassNLLCriterion_updateOutput_no_reduce_kernel: block: [0,0,0], thread: [3,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
